### ISSUE TITLE
Use "sgx_mm_modify_permissions“ to set PROT_NONE cause segment fault

### ISSUE THREAD

**Issue by jessehui** [intel/sgx-emm#1]
Hi, thank you for your great work. We are trying to adapt this new feature. However, I met a problem when using `sgx_mm_modify_permissions()` to set a range from `PROT_READ | PROT_WRITE` to `PROT_NONE`. And with GDB, I can see the segment fault throws at `do_emodpe`. This behavior doesn't seem to follow the description in the Intel manual which states that "supplying a value that does not extend the page permissions will have no effect".  I am not sure what is going wrong here.

**Comment by haitaohuang** [comment]
Thanks for reporting this. It's indeed a bug. EMOPE requires at least READ access.
Will fix soon.

**Comment by jessehui** [comment]
@haitaohuang Thank you for your quick fix! However, I tested with the new version of sgx-sdk `edmm_v5` branch but I still get segment fault. This time it happens at `do_eaccept`.  Is there any other updates I need to do to make it work? Thank you !

**Comment by haitaohuang** [comment]
There is a change in enclave_common, make sure you rebuilt it. If you are not using that in your untrusted loader, please make sure do mprotect(PROT_NONE) after eaccept. 
Also if you did not use api_test,  could you run it to confirm crash happens with intel sdk + libsgx_enclace_common.so?
If crash does happen, could you give me more details about your environment? hw, kernel, etc.
thanks

**Comment by jessehui** [comment]
@haitaohuang Thank you for your response. It is working now after I rebuilt my enclave_common.so. Thank you!
