### ISSUE TITLE
What reason would EACCEPT fail?

### ISSUE THREAD

**Issue by ghost** [intel/sgx-emm#11]
If enclave_alloc succeeds with a virtual address in-enclave, what reasons would running EACCEPT on the address fail afterwards? I get an error message when I run eaccept on a virtual address which has been previously alloced via enclave_alloc.

The return code I get matches: SGX_PAGE_ATTRIBUTES_MISMATCH, how do i fix this?

**Comment by haitaohuang** [comment]
I think this is the same as https://github.com/intel/linux-sgx/issues/948
