### ISSUE TITLE
Should `sgx_mm_enclave_pfhandler` really be allowed to `abort()` ?

### ISSUE THREAD

**Issue by lanfeust69** [intel/sgx-emm#15]
This can happen [here](https://github.com/intel/sgx-emm/blob/main/sgx_mm.c#L439).

It prevents any registered exception handler to be called. This makes for an inconsistent behavior depending if an erroneous memory access happens to be inside a range managed by EDMM or not. Typically, dereferencing a `nullptr` will be caught, but not reading in a range that has been `sgx_mm_alloc()`ed as `SGX_EMA_RESERVE` and not committed (which can be the whole point if the range is supposed to be a "guard page").

What is the reason for not returning `SGX_MM_EXCEPTION_CONTINUE_SEARCH` in this case ?

**Comment by johnvenn** [comment]
not quite understanding your point "inconsistent behavior depending if an erroneous memory access happens to be inside a range managed by EDMM or not", as I have tested with intel SGXSDK trts, enclave will be crashed on this point by accessing an address alloced for property EMA_RESERVE not commited. The address that is not commited(NOT eaccepted), in my point of view, this is considered as an illegal address for access. @haitaohuang , correct me if I was wrong.

**Comment by lanfeust69** [comment]
> enclave will be crashed on this point by accessing an address alloced for property EMA_RESERVE not commited

Yes, this is obviously an illegal address. But my point is that I don't want the enclave to be crashed, I want my exception handler always to be called before. Currently, depending on the illegal address being in the enclave range or not, my handler is called or not.

FTR, my use case is with wasmtime : the out-of-linear memory traps are implemented by handling access to pages reserved but not committed. Everything works fine if I remove the `abort()` call, else the enclave crashes.

**Comment by haitaohuang** [comment]
Hi,
Did you register a custom handler when you reserve the range? the custom handler would be called before this point. This is the last stop.

**Comment by lanfeust69** [comment]
No, I didn't register a custom **page fault** handler, as I still want the normal "commit on demand" behavior, and have no reason not to use the default mechanism for that. And no, this isn't the last stop : a custom **exception** handler is called after that (if there is no `abort`, either because it has been removed in a custom build of the sdk, or because the fault address is not in the enclave range).

Really, it boils down to the question I was asking : "What is the reason for not returning `SGX_MM_EXCEPTION_CONTINUE_SEARCH` in this case ?" 🙂 . I can't help thinking that allowing to register exception handlers that almost randomly may or may not be called is not a good idea.

**Comment by haitaohuang** [comment]
I don't understand.
Here is where custom pf handler is called: https://github.com/intel/sgx-emm/blob/main/sgx_mm.c#L396. How come it got called after this point where abort() is called?

Also confusing, you said the region was intended for "commit on demand", did you pass COMMIT_ON_DEMAND? If so, it should not get to abort(). Can you provide details on your call flow or not the code?

**Comment by lanfeust69** [comment]
I'm not interested in **page fault** handler, I'm interested in **exception** handler, registered through `sgx_register_exception_handler`.

But (in case of page fault to begin with, obviously) the default pf handler gets in the way, `abort`ing the enclave violently before my exception handler gets called. I could maybe use a custom pf handler to work around this, but with no simple access to the internals, it's hard to do the normal job that the default pf handler does, i.e. filtering the "spurious" PFs, and managing `COMMIT_ON_DEMAND` (which I currently don't use, but could).

Just returning `SGX_MM_EXCEPTION_CONTINUE_SEARCH` instead of aborting is enough to let my exception handler do its things, and if nothing handles the exception, the enclave eventually crashes anyway.

**Comment by haitaohuang** [comment]
What is that your exception handler wants to do specifically?

If the intent is to commit a page on demand, and don't have anything additional to that, then just passing COMMIT_ON_DEMAND would work?

The reason we abort() here is we don't see anything else should/can be done at this point as the comment indicated (maybe you have special reasons we would like to know). Note #PF is a special exception with EDMM enabled and EMM has to own it to do all the special handling like commit-on-demand and be the one to handle or pass down to custom handlers. 

If client wants to handle the #PF, then it needs to register one with sgx_mm APIs.    In those cases, the custom handler can do something special as needed and then likely at the end call sgx_mm_commit(), sgx_mm_commit_data(), sgx_mm_modify_x(), etc. as needed to fix the cause of #PF.

**Comment by lanfeust69** [comment]
As I tried to said briefly in a previous message, my use-case is to use wasmtime in an enclave. It manages wasm "linear memory" by reserving 8GB of memory, then committing pages "in the middle". With 32 bit addresses used by wasm, any memory access is sure to be in the reserved range, but if there is a bug in the wasm code (trying to access linear memory out of bounds), then this will trigger a PF. A handler converts that to a wasm "trap", and longjump to finish handling the call to faulty wasm code.

In a usual environment, the PF becomes a SIGSEGV handled by a signal handler. In an enclave, I can do pretty much the same with the exception handler... provided it is actually called !

Therefore, the comment "nothing should cause the PF" seems wrong in this case : it can be caused by buggy code, itself running in a supervised way, where we can handle the bug.

Moreover, as I stated, it seems strange that a buggy memory access would cause either a hard abort, or a call to the registered exception handler, randomly depending if the garbarge interpreted as an address happens to lie in the enclave range or not.

**Comment by haitaohuang** [comment]
It seems possible you can achieve the same thing by registering a custom PF handler for the reserved guard regions. Just a little extra code to wrapper your signal handler or have your custom PF handler just return SGX_MM_EXCEPTION_CONTINUE_SEARCH, correct?  if so, that's may be the quickest way to solve your problem. 

I think we made it abort() in general when we exhausted all known legit cases (assuming buggy cases are not secure). This is more like defense-in-depth. Need more time to discuss  with team if we want to change this design.
