### ISSUE TITLE
Is is possible to optimize `ema_modify_permissions()`?

### ISSUE THREAD

**Issue by Bonjourz** [intel/sgx-emm#2]
Hi @haitaohuang , thank you for your great contribution. We are trying to adapt this new feature and I'm the person who is focusing on the new EDMM feature. I have some questions on the implementation. For the `ema_modify_permissions()`, it seems that we always invoke `do_emope()` ([Line 918 in ema.c](https://github.com/intel/sgx-emm/blob/main/ema.c#L918)), even if we only extend the permission (For example, from R to RW, or from R to RE). The similar operations exist for [`do_emopr()`](https://github.com/intel/linux-sgx/blob/edmm_v5/psw/enclave_common/sgx_mm_ocalls.cpp#L407).

I wonder why we do not use the some functions like [`check_vrds_pr_pe_needed()`](https://github.com/intel/linux-sgx/blob/sgx_2.17/sdk/tmm_rsrv/mm_vrd.cpp#L510) to determine whether invoke `EMODPE` and `EMODPR` for different inputs from user? I guess it is because it may increase the complexity of implementation here.

**Comment by haitaohuang** [comment]
right, we probably can optimize out some of emodpr (outside enclave, e.g.,  enclave_common) and emodpe (inside enclave). But I suspect change permissions would not be a frequent operation in most use cases. emodpe would not be significant overhead. So for now we keep it simple. Would welcome any feedback if you have some data/use cases that require more optimization in this flow.

**Comment by Bonjourz** [comment]
Get it! Thanks for your reply!
