### ISSUE TITLE
[Question] Is there a way to identify the PF reason by PF error code?

### ISSUE THREAD

**Issue by jessehui** [intel/sgx-emm#9]
I defined two different paths to commit pages or extend permissions on demand. I would like to know if the PF is triggered by the uncommitted pages or permission violation. A way to do it is to traverse my page tracking structure to find if the page containing the page fault address is committed or not. However, this is not efficient enough. And I am thinking to use the pfec struct.

I was thinking of using "P-bit" which indicates if the page is present. But it seems under both cases, the page is present, which I assume is EADD-ed by the driver.

Is there any other way? Is this possible to identify the reason for the PF given the pfec struct?

**Comment by haitaohuang** [comment]
Can u describe the calling sequence? Are you checking PFEC in your own PF handler as described in sgx_mm_alloc API?
